// Generated by LiveScript 1.2.0
var DEBUG, UNIVERSE_COLLECTION, out$ = typeof exports != 'undefined' && exports || this;
DEBUG = true;
UNIVERSE_COLLECTION = 'Blueprint';
(function(){
  var console, _, Fs, Path, Uuid, Da_Funk, reset;
  console = require('console');
  _ = require('lodash');
  Fs = require('fs');
  Path = require('path');
  Uuid = require('node-uuid');
  Da_Funk = require('./da_funk');
  _ = require('lodash');
  return out$.reset = reset = function(applicationContext){};
})();