// Generated by LiveScript 1.2.0
(function(){
  'use strict';
  var f, users, sessions;
  require('console').log('%s', 'tearing down app ' + applicationContext.name);
  f = require('org/arangodb/foxx/authentication');
  users = new f.Users(applicationContext);
  users.teardown();
  sessions = new f.Sessions(applicationContext);
  return sessions.teardown();
})();